site_name: msdb

theme:
  name: "material"  
  features:
    - content.code.copy
 
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/g-patin/msdb
      name: GitHub

  
nav:
  - index.md
  - installation.md    
  - Tutorials:  
      - get-started.md   
  - How-to-guides:  
      - Create an DB class instance: create-DB-class-instance.md    
      - create-databases.md 
      - Manage the db_config file: manage_db_config.md 
  - Explanation:
      - databases-files.md
      - db_config file: db_config.md
      - package-usage.md      
  - References: references.md 
  
plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      handlers:
        python:
          paths: ['src']  # Make sure mkdocstrings looks in the 'src' directory
          
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - codehilite
  - pymdownx.superfences
  - toc:
      permalink: true
      
extra_css:
  - css/custom.css
  
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
